name: "Download Post Migration DB"
description: "Downloads a post-migration DB artifact and unpacks it into the destination path"

inputs:
  artifact-url:
    description: "Artifact URL"
    required: true
  destination-path:
    description: "Destination directory"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download
      env:
        ARTIFACT_URL: ${{ inputs.artifact-url }}
        DESTINATION_PATH: ${{ inputs.destination-path }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      shell: bash
      run: |
        set -euo pipefail
        TMP_DIR="$(mktemp -d)"

        FILENAME=$(basename ${ARTIFACT_URL})

        IS_GITHUB=$(echo ${ARTIFACT_URL}| grep -o github || true)
        IS_ZIP=$(echo ${ARTIFACT_URL}| grep -o zip || true)
        if [[ $IS_GITHUB == "github" ]];then
          curl -sSLf -H "Authorization: Bearer ${GITHUB_TOKEN}" -o "${TMP_DIR}/${FILENAME}" "${ARTIFACT_URL}"
        else
          curl -sSLf -o "${TMP_DIR}/${FILENAME}" "${ARTIFACT_URL}"
        fi;

        rm -rf "${DESTINATION_PATH}"
        mkdir -p "${DESTINATION_PATH}"

        if [[ $IS_ZIP == "zip" ]];then
          unzip -q "${TMP_DIR}/${FILENAME}" -d "${DESTINATION_PATH}"
        else
          tar -xvf "${TMP_DIR}/${FILENAME}" -C "${DESTINATION_PATH}"
        fi;

        rm -rf "${TMP_DIR}"
        echo "ls dst path"
        ls "${DESTINATION_PATH}"
        mv ${DESTINATION_PATH}/pahm/spawn ${DESTINATION_PATH}/
        mv ${DESTINATION_PATH}/pahm/ready.json ${DESTINATION_PATH}/
        mv ${DESTINATION_PATH}/pahm/ports.json ${DESTINATION_PATH}/
        echo "ls dst path"
        ls "${DESTINATION_PATH}"
