endpoint: ${env.POLKADOT_RPC}:${env.AH_NODE_RPC_PORT}
mock-signature-host: true
db: ./dbs/polkadot-asset-hub.sqlite
runtime-log-level: 5

wasm-override: ./runtime_wasm/asset_hub_polkadot_runtime.compact.compressed.wasm
# resume: true