endpoint: ${env.POLKADOT_RPC}:${env.RELAY_NODE_RPC_PORT}
mock-signature-host: true
db: ./dbs/polkadot.sqlite
runtime-log-level: 5

wasm-override: ./runtime_wasm/polkadot_runtime.compact.compressed.wasm
# resume: true
