name: Check Submodule Consistency

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check submodule consistency
        shell: bash
        run: |
          echo "🔍 Checking submodule consistency with SUBMODULES.yaml..."

          # Parse SUBMODULES.yaml and compare with actual submodule commits
          failed=false

          # Read SUBMODULES.yaml line by line
          while IFS=': ' read -r module expected_commit || [[ -n "$module" ]]; do
            # Skip comments and empty lines
            if [[ $module =~ ^#.*$ ]] || [[ -z "$module" ]] || [[ -z "$expected_commit" ]]; then
              continue
            fi

            # Trim whitespace
            module=$(echo "$module" | xargs)
            expected_commit=$(echo "$expected_commit" | xargs)

            # Get actual commit from git submodule status
            actual_commit=$(git submodule status "$module" 2>/dev/null | awk '{print $1}' | sed 's/^[+-]//')

            if [[ -z "$actual_commit" ]]; then
              echo "❌ Submodule '$module' not found or not initialized"
              failed=true
            elif [[ "$actual_commit" != "$expected_commit" ]]; then
              echo "❌ Submodule '$module' mismatch:"
              echo "   Expected: $expected_commit"
              echo "   Actual:   $actual_commit"
              failed=true
            else
              echo "✅ Submodule '$module' matches expected commit: $expected_commit"
            fi
          done < SUBMODULES.yaml

          if $failed; then
            echo ""
            echo "💡 To fix this:"
            echo "1. Check out the correct commits in each submodule directory"
            echo "2. Or update SUBMODULES.yaml with the current commits you want to lock to"
            echo "3. Commit the submodule pointer updates: git add . && git commit -m 'Update submodules'"
            exit 1
          fi

          echo "🎉 All submodules match their expected commits!"
