name: Migration Schedule Check

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'run-id to download the snaps, if not provided we will use the latest ones.'
        required: false
      network:
        description: 'Network to use (default kusama)'
        default: 'kusama'
        type: choice
        options:
          - kusama
          - polkadot

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  get-run-id:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.run-id == '') || 'true' }}
    outputs:
      RUN_ID: ${{ steps.get_run_id.outputs.RUN_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: get_run_id
        id: get_run_id
        uses: ./.github/actions/get-latest-ahm-run-id
        with:
          gh-token: ${{ github.token }}
          network: ${{ inputs.network || 'kusama' }}

      - name: verify
        shell: bash
        run: |
          echo "RUN_ID: ${{ steps.get_run_id.outputs.RUN_ID }}"

  migration_schedule_check_with_id:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run-id != '' }}
    uses: ./.github/workflows/migration-schedule-check-common.yml
    with:
      network: ${{ inputs.network }}
      run-id: ${{ inputs.run-id }}

  migration_schedule_check_without_id:
    needs: [get-run-id]
    uses: ./.github/workflows/migration-schedule-check-common.yml
    with:
      network: ${{ inputs.network }}
      run-id: ${{ inputs.run-id }}


