name: Run-Orchestrator-polkadot

on:
  workflow_dispatch:
    inputs:
      artifacts-run-id:
        required: false
        type: string
        description: 'Run-id to use the artifacts to spawn the network'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}
env:
  AHM_BASE_PATH: "/tmp/ahm"
  AHM_BINS: "/tmp"
  ZOMBIE_CI: 1

jobs:
  run_orchestrator_polkadot:
    runs-on: parity-large-persistent
    container:
      image: docker.io/paritytech/ci-unified:bullseye-1.88.0-2025-06-27-v202506301118
    timeout-minutes: 2880 # 2 days

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: extractions/setup-just@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: set_run_id
        id: set_run_id
        shell: bash
        env:
          ARTIFACTS_RUN_ID: ${{ inputs.artifacts-run-id }}
        run: |
          if [[ $ARTIFACTS_RUN_ID != "" ]]; then
            echo "RUN_ID_SET=true" >> $GITHUB_OUTPUT
          fi;

      - name: download_polkadot_binaries
        uses: ./.github/actions/download-polkadot-binaries
        with:
          tag-version: "polkadot-stable2503-7"
          destination-path: ${{ env.AHM_BINS }}

      - name: download_doppelganger_binaries
        uses: ./.github/actions/download-doppelganger-binaries
        with:
          destination-path: ${{ env.AHM_BINS }}

      - name: download_artifacts
        id: download_artifacts
        shell: bash
        if: ${{ steps.set_run_id.outputs.RUN_ID_SET == 'true' }}
        env:
          ARTIFACTS_RUN_ID: ${{ inputs.artifacts-run-id }}
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ $ARTIFACTS_RUN_ID != "" ]]; then
            echo "downloading artifacts from https://github.com/paritytech/ahm-dryrun/actions/runs/${ARTIFACTS_RUN_ID}"
            gh run download $ARTIFACTS_RUN_ID
            ls -ltr
            ARTIFACTS_DIR=$(ls -t |head -1)
            echo "ARTIFACTS_DIR=$ARTIFACTS_DIR" >> $GITHUB_OUTPUT
          else
            echo "No artifact run id provided, skipping step"
          fi

      - name: run_orchestrator
        id: run_orchestrator
        shell: bash
        env:
          ARTIFACTS_RUN_ID: ${{ inputs.artifacts-run-id }}
          GH_TOKEN: ${{ github.token }}
        run: |
          # export path
          export PATH=${AHM_BINS}:$PATH

          if [[ $ARTIFACTS_RUN_ID != "" ]]; then
            echo "::group::install_zombie-cli"
            cargo install zombie-cli -f
            echo "::endgroup::"

            echo "::group::npm"
            npm install
            npm run build
            echo "::endgroup::"

            echo "::group::zombie_config"
            ls -l ${{ steps.download_artifacts.outputs.ARTIFACTS_DIR }}
            cat ${{ steps.download_artifacts.outputs.ARTIFACTS_DIR }}/config.toml
            echo "::endgroup::"

            echo "::group::exports"
            export AHM_STEP=1
            export AHM_BASE_PATH="$(pwd)/${{ steps.download_artifacts.outputs.ARTIFACTS_DIR }}"
            export RUST_LOG=zombie=debug
            echo "::warning::PATH: $PATH"
            echo "::endgroup::"

            echo "::group::zombie-cli"
            cd ${{ steps.download_artifacts.outputs.ARTIFACTS_DIR }}
            nohup zombie-cli spawn -p native -d /tmp/spawn config.toml > nohup.out 2> nohup.err &
            ZOMBIE_FILE="/tmp/spawn/zombie.json"
            until [ -f "$ZOMBIE_FILE" ]; do
              echo "ZOMBIE_FILE: $ZOMBIE_FILE not present yet"
              sleep 2
            done
            echo "'zombie.json' file present, network spawned... sleeping a few seconds"
            echo "::endgroup::"

            echo "::group::zombie-cli-output"
            cat nohup.out
            echo "::endgroup::"

            echo "sleeping 1 min to bootstrap"
            sleep 60

            echo "::group::alice-output"
            cat /tmp/spawn/alice/alice.log
            echo "::endgroup::"

            npm run polkadot-migration
          else
            just run-ahm-polkadot
          fi

      - name: upload_artifacts
        uses: actions/upload-artifact@v4
        if: ${{ steps.run_orchestrator.conclusion == 'success' }}
        with:
          name: polkadot-ahm-${{ github.sha }}
          path: |
            /tmp/spawn

      # if fails upload only the node logs
      - name: upload_artifacts
        uses: actions/upload-artifact@v4
        if: ${{ steps.run_orchestrator.conclusion == 'failure' }}
        with:
          name: polkadot-ahm-${{ github.sha }}
          path: |
            /tmp/spawn/alice/alice.log
            /tmp/spawn/bob/bob.log
            /tmp/spawn/collator/collator.log
